### ISSUE TITLE
Minifying error

### ISSUE THREAD

**Issue by ScHc4043** [Gork3m/IronBrew2-Deobfuscator#1]
[*] Starting.. [*] Loaded script [!] Minifying... Unhandled exception. System.ComponentModel.Win32Exception (2): The system cannot find the file specified.    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)    at System.Diagnostics.Process.Start()    at IronBrew2_Deobfuscator.Deobfuscator.MinifyScript(String script, String path) in C:\Users\Owner\Desktop\IronBrew2-Deobfuscator-main\IronBrew2 Deobfuscator\IronBrew2 Deobfuscator\Deobfuscator.cs:line 36    at IronBrew2_Deobfuscator.Deobfuscator.DeobfuscateScript(String script) in C:\Users\Owner\Desktop\IronBrew2-Deobfuscator-main\IronBrew2 Deobfuscator\IronBrew2 Deobfuscator\Deobfuscator.cs:line 64    at CLI.Program.Main(String[] args) in C:\Users\Owner\Desktop\IronBrew2-Deobfuscator-main\IronBrew2 Deobfuscator\CLI\Program.cs:line 16

**Comment by JollycREAL** [comment]
put the util folder in the dir where the deobfuscator is (most likely will still error with something diff because its a wip I think)

**Comment by TheGreatSageEqualToHeaven** [comment]
Fixed
